import type { Metadata } from "next";
import "../globals.css";
import { locales, defaultLocale, messages } from "@/i18n/config";
import ClientI18nProvider from "@/i18n/ClientI18nProvider";

export const metadata: Metadata = {
  title: "Remax Website",
  description: "Generated by create next app",
};

// Geçerli dil parametrelerini tanımla
export async function generateStaticParams() {
  return locales.map((lang) => ({ lang }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  // Geçerli dili al - await ile bekleyelim
  const resolvedParams = await Promise.resolve(params);
  const lang = resolvedParams.lang || defaultLocale;
  
  // Dil mesajlarını al
  const langMessages = messages[lang as keyof typeof messages] || messages[defaultLocale];

  return (
    <ClientI18nProvider locale={lang} messages={langMessages}>
      {children}
    </ClientI18nProvider>
  );
} 