import type { Metadata } from "next";
import "./globals.css";
import { defaultLocale } from "@/i18n/config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params?: { lang?: string };
}>) {
  // Varsayılan dil kullanılır, alt layout'ta özel dil ayarlanacak
  const resolvedParams = await Promise.resolve(params || {});
  const lang = resolvedParams.lang || defaultLocale;
  
  return (
    <html lang={lang} suppressHydrationWarning>
      <body>
        {children}
      </body>
    </html>
  );
}
