import type { Metadata } from "next";
import "./globals.scss";
import { defaultLocale } from "@/i18n/config";
import '@/styles/main.scss';
import NextTopLoader from 'nextjs-toploader';
import { Inter } from 'next/font/google';

// Inter fontunu tanımlama
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params?: { lang?: string };
}>) {
  // Params'ı await ediyoruz
  const awaitedParams = await params;
  
  // Varsayılan dil kullanılır, alt layout'ta özel dil ayarlanacak
  const lang = String(awaitedParams?.lang || defaultLocale);
  
  return (
    <html lang={lang} className={`${inter.variable}`}>
      <body suppressHydrationWarning>
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
